"""Generate a 1-bit GFX font from Departure Mono 1.500 (Pillow required).

Usage: python generate_departure_font.py DepartureMono-Regular.otf
Output is a C++ header on stdout. 0x7f contains the right-arrow glyph.
"""
import sys
from PIL import ImageFont

font = ImageFont.truetype(sys.argv[1], 11)
bitmap, glyphs = [], []
for code in range(32, 128):
    char = chr(code) if code < 127 else "\u2192"
    mask, offset = font.getmask2(char, mode="1", anchor="ls")
    width, height = mask.size
    pixels = list(mask)
    start = len(bitmap)
    for bit in range(0, len(pixels), 8):
        value = 0
        for shift, pixel in enumerate(pixels[bit:bit + 8]):
            if pixel:
                value |= 0x80 >> shift
        bitmap.append(value)
    glyphs.append((start, width, height, round(font.getlength(char)), *offset))

print("""#pragma once
// Departure Mono 1.500 by Helena Zhang, SIL OFL 1.1.
// Rasterized at the recommended 11px grid, monochrome, no smoothing.
// ASCII + right arrow at 0x7f. See DEPARTURE-MONO-LICENSE.txt.
// Generated by arduino/tools/generate_departure_font.py.
#include <Arduino_GFX_Library.h>
const uint8_t DepartureMono11Bitmaps[] PROGMEM = {""")
for start in range(0, len(bitmap), 16):
    print("  " + ", ".join(f"0x{value:02X}" for value in bitmap[start:start+16]) + ",")
print("};\nconst GFXglyph DepartureMono11Glyphs[] PROGMEM = {")
for glyph in glyphs:
    print("  {" + ", ".join(map(str, glyph)) + "},")
print("};\nconst GFXfont DepartureMono11 PROGMEM = {(uint8_t*)DepartureMono11Bitmaps, (GFXglyph*)DepartureMono11Glyphs, 0x20, 0x7f, 11};")
