"""Generate device GFX fonts: python generate_barlow_font.py FONT.ttf OUTPUT_DIR [SIZE ...].

Requires Pillow. Barlow Condensed is SIL OFL 1.1; keep its license
with these generated headers. ETA and distance values use separate numeral fonts in the UI.
"""
import sys
from pathlib import Path
from PIL import ImageFont

style = Path(sys.argv[1]).stem.removeprefix('BarlowCondensed-')
if style not in ('Regular', 'SemiBold', 'Bold', 'Italic'):
    raise ValueError('Expected BarlowCondensed-Regular, -SemiBold, -Bold, or -Italic.ttf')
out = Path(sys.argv[2])
out.mkdir(parents=True, exist_ok=True)
for size in (tuple(map(int, sys.argv[3:])) if len(sys.argv) > 3 else (12, 16, 20, 24)):
    font = ImageFont.truetype(sys.argv[1], size)
    name = f'BarlowCondensed{style}{size}'
    bitmap, glyphs = [], []
    for code in range(32, 128):
        mask, offset = font.getmask2(chr(code) if code < 127 else '\u2192', mode='L', anchor='ls')
        width, height = mask.size
        pixels = list(mask)
        start = len(bitmap)
        for bit in range(0, len(pixels), 8):
            value = 0
            for shift, pixel in enumerate(pixels[bit:bit+8]):
                if pixel >= 100:
                    value |= 0x80 >> shift
            bitmap.append(value)
        glyphs.append((start, width, height, round(font.getlength(chr(code) if code < 127 else '\u2192')), *offset))
    lines = ['#pragma once', '// Copyright 2017 The Barlow Project Authors (https://github.com/jpt/barlow)',
             '// SIL OFL 1.1. See BARLOW-CONDENSED-LICENSE.txt in the sketch root.',
             f'// Barlow Condensed {style}, {size}px. Generated by tools/generate_barlow_font.py.',
             '#include <Arduino_GFX_Library.h>', f'const uint8_t {name}Bitmaps[] PROGMEM = {{']
    for start in range(0, len(bitmap), 16):
        lines.append('  ' + ', '.join(f'0x{v:02X}' for v in bitmap[start:start+16]) + ',')
    lines += ['};', f'const GFXglyph {name}Glyphs[] PROGMEM = {{']
    lines += ['  {' + ', '.join(map(str, g)) + '},' for g in glyphs]
    lines += ['};', f'const GFXfont {name} PROGMEM = {{(uint8_t*){name}Bitmaps, (GFXglyph*){name}Glyphs, 0x20, 0x7f, {size+3}}};']
    (out / f'{name}.h').write_text('\n'.join(lines) + '\n')
